version: 0.2

phases:
  install:
    commands:
      - echo "$(lsb_release -cs)"
      - apt-get update -y
      - apt-get install -y apt-transport-https ca-certificates software-properties-common
      - add-apt-repository -y ppa:openjdk-r/ppa
      - sudo apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
      - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      - apt-get update -y
      - apt-get install -y sbt
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket codepipeline-ap-southeast-1-355963742768 --output-template-file outputSamTemplate.yaml
artifacts:
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml