AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: scala hello world
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::main
      Runtime: java 8
      CodeUri: https://s3-ap-southeast-1.amazonaws.com/codepipeline-ap-southeast-1-355963742768/