AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: scala hello world
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::main
      Runtime: java 8
      CodeUri: ./target/scala-2.12/HelloDocker-Sbt-assembly-1.0.jar